version: '3.9'

services:
  postgres:
    image: postgres:15.3-alpine
    restart: on-failure
    env_file:
      - ./confs/docker_compose_envs/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_grpc:
    image: django_grpc:latest
    command: sh -c "/wait && python manage.py runserver 0.0.0.0:8000"
    build: .
    restart: on-failure
    env_file:
      - ./confs/docker_compose_envs/django_grpc.env
    volumes:
      - .:/django_grpc
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
