#!/bin/bash

# ###############
# Git
# #####
function git.pre_commit.init() {
  pre-commit install
  pre-commit install --hook-type pre-push
  pre-commit install --hook-type commit-msg
}

function git.pre_commit.run_for_all() {
  pre-commit run --all-files;
}

# ###############
# Requirements
# #####
function requirements.compile() {
  pip install -r requirements/prerequisite/pip-tools.txt
  pip-compile requirements/raw/prod.in -o requirements/compiled/prod.txt
  pip-compile requirements/raw/dev.in -o requirements/compiled/dev.txt
}

function requirements.install() {
  pip install -r requirements/prerequisite/pip-tools.txt
  pip-sync requirements/compiled/dev.txt
}

# ###############
# Docker
# #####
function _docker.compose_base() {
  docker compose -f docker-compose.base.yml -f docker-compose.dev.yml "$@"
}

function docker.destroy() {
  _docker.compose_base down -v
}

# ###############
# Postgres
# #####
function postgres.shell() {
  _docker.compose_base up -d postgres
  _docker.compose_base exec postgres /bin/bash
}

# ###############
# Django gRPC
# #####
function django_grpc.runserver() {
  _docker.compose_base up
}

function django_grpc.makemigrations() {
  _docker.compose_base run --rm django_grpc sh -c "/wait && python manage.py makemigrations"
}
function django_grpc.migrate() {
  _docker.compose_base run --rm django_grpc sh -c "/wait && python manage.py migrate"
}

# ###############
# Runner (should be at the end of the file)
# #####
eval "${1}" "${@:2}"
