#!/bin/bash

# ###############
# Share
# #####
function _change_the_files_owner_to_the_current_user() {
  echo "Changing the owner of the project files to '$USER'"
  sudo chown -R "$USER": *
}

# ###############
# Git
# #####
function git.pre_commit.init() {
  pre-commit install
  pre-commit install --hook-type pre-push
  pre-commit install --hook-type commit-msg
}

function git.pre_commit.run_for_all() {
  pre-commit run --all-files;
}

# ###############
# Requirements
# #####
function requirements.compile() {
  pip install -r requirements/prerequisite/pip-tools.txt
  pip-compile requirements/raw/prod.in -o requirements/compiled/prod.txt
  pip-compile requirements/raw/dev.in -o requirements/compiled/dev.txt
}

function requirements.install.dev() {
  pip install -r requirements/prerequisite/pip-tools.txt
  pip-sync requirements/compiled/dev.txt
}

function requirements.install.prod() {
  pip install -r requirements/prerequisite/pip-tools.txt
  pip-sync requirements/compiled/prod.txt
}

# ###############
# Docker
# #####
function docker.build() {
  docker compose build
}

function docker.destroy() {
  docker compose down -v
}

function docker.down() {
  docker compose down
}

function docker.stop() {
  docker compose stop
}

# ###############
# Postgres
# #####
function postgres.shell() {
  docker compose up -d postgres
  docker compose exec postgres /bin/bash
}

# ###############
# Django gRPC (The main application)
# #####
function app.shell() {
  docker compose up -d django_grpc
  docker compose exec django_grpc /bin/bash
}

function app.runserver() {
  docker compose up
  _change_the_files_owner_to_the_current_user  # For the .pyc files
}

function app.makemigrations() {
  docker compose run --rm django_grpc sh -c "/wait && python manage.py makemigrations $*"
  _change_the_files_owner_to_the_current_user
}

function app.migrate() {
  docker compose run --rm django_grpc sh -c "/wait && python manage.py migrate $*"
}

function app.collectstatic() {
  docker compose run --rm django_grpc sh -c "/wait && python manage.py collectstatic $*"
  _change_the_files_owner_to_the_current_user
}

function app.makemessages() {
  docker compose run --rm django_grpc sh -c "/wait && python manage.py makemessages $*"
  _change_the_files_owner_to_the_current_user
}

function app.compilemessages() {
  docker compose run --rm django_grpc sh -c "/wait && python manage.py compilemessages $*"
  _change_the_files_owner_to_the_current_user
}

function app.createsuperuser() {
  docker compose run --rm django_grpc sh -c "/wait && python manage.py createsuperuser $*"
}

function app.provision() {
  docker compose run --rm django_grpc sh -c "/wait && ./confs/docker_compose_scripts/django_grpc_provision.sh"
  _change_the_files_owner_to_the_current_user
}

# ###############
# Runner (should be at the end of the file)
# #####
eval "${1}" "${@:2}"
